### ISSUE TITLE
Actividad 9 corregida: Fallo (Ver descripción)

### ISSUE THREAD

**Issue by cborcar637** [pperval015/Unidad-3#9]
Aunque funciona correctamente, en cada iteración estás mostrando el resultado al usuario y lo correcto sería hacerlo una sola vez al finalizar el cálculo del factorial. En otras palabras, la línea de código `document.getElementById("solucion").innerHTML = "El factorial de " + numero + " es " + resultado;` debería de ponerse fuera del bucle.

Cuando lo soluciones, no cierres la petición, simplemente responde a este mensaje para saber que lo has arreglado. Ya te pediré que lo cierres cuando lo revise.

**Comment by pperval015** [comment]
Ya lo he corregido

**Comment by cborcar637** [comment]
Revisado
